backend:
  name: git-gateway
local_backend: true
show_preview_links: false
editor:
  preview: false
media_folder: _includes/assets/images
collections:
  - name: exercise
    label: Exercise
    format: frontmatter
    create: true
    folder: sprint-guide/exercises
    fields:
      - {name: title, widget: string}
      - label: "Tags"
        name: "tags"
        hint: "'exercise' must be present"
        widget: "select"
        multiple: true
        min: 1
        options:
          - exercise
          - prepare
          - understand
          - diverge
          - converge
          - prototype
          - test
          - analyse
        default: ["exercise"]
      - {name: body, widget: markdown}
  - name: schedule
    label: Schedule
    format: json
    create: true
    folder: _data/sprint_guide/schedules
    fields:
      - {name: title, widget: string}
      - {name: duration, widget: string}
      - {name: introduction, widget: markdown}
      - name: phases
        widget: list
        fields:
          - {name: title, widget: string}
          - {label: End Time, name: end_time, widget: string, required: false}
          - name: exercise
            widget: list
            fields:
              - {name: title, widget: string}
              - {name: time, widget: string, required: false}
              - {name: divider, widget: boolean, required: false}
              - name: slug
                label: Exercise
                hint: "Leave blank for breaks etc."
                widget: relation
                collection: exercise
                value_field: "{{slug}}"
                search_fields: ["title"]
                display_fields: ["title"]
                required: false
  - label: "Glossary"
    name: "glossary"
    files:
      - name: glossary
        label: Glossary Terms
        file: "_data/sprint_guide/glossary.json"
        fields:
          - name: terms
            label: Terms
            widget: list
            fields:
              - {name: title, widget: string}
              - {name: definition, widget: text}
  - label: "Resource"
    name: "resource"
    files:
      - name: resource_reading
        label: "Resources (Reading)"
        file: "_data/sprint_guide/resources/reading.json"
        fields:
          - name: resources
            label: Resources
            widget: list
            fields:
            - {name: title, widget: string}
            - {name: description, widget: string}
            - {name: url, widget: string}
            - name: icon
              widget: image
              choose_url: false
              media_folder: '/_includes/assets/images/sprint_guide/resources'
            - name: "tags"
              widget: "select"
              multiple: true
              options: ["Blog", "Book", "Wiki"]
              default: ["Book"]
      - name: resource_software
        label: "Resources (Software)"
        file: "_data/sprint_guide/resources/software.json"
        fields:
          - name: resources
            label: Resources
            widget: list
            fields:
            - {name: title, widget: string}
            - {name: description, widget: string}
            - {name: url, widget: string}
            - name: icon
              widget: image
              choose_url: false
              media_folder: '/_includes/assets/images/sprint_guide/resources'
            - name: "tags"
              widget: "select"
              multiple: true
              options: ["Whiteboard", "Prototyping", "Video Calling", "User Testing", "Prototyping"]
              default: ["Whiteboard"]
      - name: resource_template
        label: "Resources (Template)"
        file: "_data/sprint_guide/resources/templates.json"
        fields:
          - name: resources
            label: Resources
            widget: list
            fields:
              - {name: title, widget: string}
              - {name: description, widget: string}
              - {name: url, widget: string}
              - name: icon
                widget: image
                choose_url: false
                media_folder: '/_includes/assets/images/sprint_guide/resources'
              - name: "tags"
                widget: "select"
                multiple: true
                options: ["Trello", "Schedule"]
                default: ["Trello"]
